# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Publish Storm SNAPSHOTs

on:
  workflow_dispatch: { }
  schedule:
    # every day 5min after midnight, UTC.
    - cron: "5 0 * * *"

jobs:
  upload_to_nightlies:
    if: github.repository == 'apache/storm'
    name: Publish Snapshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
        with:
          path: ~/.m2/repository
          key: snapshots-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            snapshots-maven-
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.10'
      - name: Set up Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 16
      - name: Set up Ruby
        uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
        with:
          ruby-version: '2.7'
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: temurin
          java-version: 20
      - id: extract_version
        name: Extract project version
        shell: bash
        run: |
          VERSION=$(mvn exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive -q)
          if [[ "$VERSION" == *"SNAPSHOT"* ]]; then
             echo "snapshot=SNAPSHOT" >> $GITHUB_OUTPUT
          fi
      - name: Ensure a clean state without storm artifacts
        if: steps.extract_version.outputs.snapshot == 'SNAPSHOT'
        run: rm -rf ~/.m2/repository/org/apache/storm
      - name: Set up project dependencies
        if: steps.extract_version.outputs.snapshot == 'SNAPSHOT'
        run: /bin/bash ./dev-tools/gitact/gitact-install.sh `pwd`
      - name: Deploy Maven snapshots
        if: steps.extract_version.outputs.snapshot == 'SNAPSHOT'
        env:
          ASF_USERNAME: ${{ secrets.NEXUS_USER }}
          ASF_PASSWORD: ${{ secrets.NEXUS_PW }}
        run: |
          echo "<settings><servers><server><id>apache.snapshots.https</id><username>$ASF_USERNAME</username><password>$ASF_PASSWORD</password></server></servers></settings>" > settings.xml
          mvn --settings settings.xml -U -B -e -fae -ntp -DskipTests -P !examples deploy